using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using Common;
using GD_NHANVIEN.DAL;
using GD_NHANVIEN;
namespace GD_NHANVIEN.GUI
{
    public partial class ChiTietHDTC : DevExpress.XtraEditors.XtraForm
    {
        
        public string idsim1 = "";
        public string idkh = "";
        public string idcthd;
        public ChiTietHDTC(string idsim,string idhd)
        {
            InitializeComponent();
            HoaDonTCDAL dal = new HoaDonTCDAL();
            ChiTietHDTCDAL dao = new ChiTietHDTCDAL();
            txtidsim.Text = dal.GetPrintSim(Convert.ToInt32(idsim));
            txtmakh.Text = dal.GetPrintMaKH(Convert.ToInt32(idsim));
            idsim1 = idsim;
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //Model.EFModel.QLCuocDTContext dbContext = new Model.EFModel.QLCuocDTContext();
            //// Call the Load method to get the data for the given DbSet from the database.
            //dbContext.ChitietHDTCs.Load();
            // This line of code is generated by Data Source Configuration Wizard

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext

            // This line of code is generated by Data Source Configuration Wizard
            var a = Convert.ToInt32(idhd);
            chiTietHDTCsBindingSource.DataSource = dao.Load(a);
        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            
        }

        private void simpleButton1_Click_1(object sender, EventArgs e)
        {
            
            
        }

        private void txtnam_TextChanged(object sender, EventArgs e)
        {

        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
           
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            

        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void simpleButton1_Click_2(object sender, EventArgs e)
        {
            if(txtngayhd.Text=="")
            {
                MessageBox.Show("Vui lòng chọn thông tin để xem", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            else
            {
                CTCG f = new CTCG(idcthd);
                f.Show();
            }
            
        }

        private void gridControl1_Click_1(object sender, EventArgs e)
        {
            txtngayhd.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "NgayHD").ToString();
            idcthd= gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "ChiTietHDTCID").ToString();
        }
    }
}