using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using Model.EFModel;
namespace GD_NHANVIEN.GUI
{
    public partial class CTCG : DevExpress.XtraEditors.XtraForm
    {
        QLCuocDTContext db = new QLCuocDTContext();
        public CTCG(string idcthd)
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //Model.EFModel.QLCuocDTContext dbContext = new Model.EFModel.QLCuocDTContext();
            //// Call the Load method to get the data for the given DbSet from the database.
            //dbContext.ChiTietCuocGois.Load();
            // This line of code is generated by Data Source Configuration Wizard
            int a = Convert.ToInt32(idcthd);
            var res = db.ChiTietCuocGois.Where(s => s.ChiTietHDTCID == a).ToList();
            chiTietCuocGoisBindingSource.DataSource = res;
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            this.Close();
        }
    }
}