using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using GD_NHANVIEN.DAL;
namespace GD_NHANVIEN.GUI
{
    public partial class Khachhang : DevExpress.XtraEditors.XtraForm
    {
        public Khachhang()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext

            // Call the Load method to get the data for the given DbSet from the database.

            var result = dal.Load();
            khachHangsBindingSource1.DataSource = result;
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //Model.EFModel.QLCuocDTContext dbContext = new Model.EFModel.QLCuocDTContext();
            //// Call the Load method to get the data for the given DbSet from the database.
            //dbContext.KhachHangs.Load();
            //// This line of code is generated by Data Source Configuration Wizard
            //khachHangsBindingSource1.DataSource = dbContext.KhachHangs.Local.ToBindingList();
        }
        KhachHangDAL dal = new KhachHangDAL();
        public void Clear()
        {
            txtmakh.Clear();
            txttenkh.Clear();
            txtcmnd.Clear();
            txtchucvu.Clear();
            txtdiachi.Clear();
            txtnn.Clear();
            txtemail.Clear();
            khachHangsBindingSource1.DataSource = dal.Load();

        }
        public void ClearKH()
        {
            txtmakh.Clear();
            txttenkh.Clear();
            txtcmnd.Clear();
            txtchucvu.Clear();
            txtdiachi.Clear();
            txtnn.Clear();
            txtemail.Clear();
            

        }

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            
            try
            {
                if (txttenkh.Text == "" || txtcmnd.Text == "" || txtnn.Text == "" || txtchucvu.Text == "" || txtdiachi.Text == "")
                {
                    MessageBox.Show("Vui lòng nhập đầy đủ thông tin", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);

                }
                else if(dal.testnumber(txtcmnd.Text)==0)
                {
                    MessageBox.Show("Số CMND chỉ được nhập số", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
                else if(dal.testcmnd(txtcmnd.Text)==0)
                {
                    MessageBox.Show("Số CMND không hợp lệ", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
                else
                {
                    dal.ThemKH(txttenkh.Text, txtcmnd.Text, txtnn.Text, txtchucvu.Text, txtdiachi.Text,txtemail.Text);
                    MessageBox.Show("Thêm khách hàng thành công", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Asterisk);
                    Clear();
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Đã có lỗi xảy ra!");
            }

        }

        private void textBox2_TextChanged(object sender, EventArgs e)
        {

        }

        private void bangkh_Click(object sender, EventArgs e)
        {
            
        }

        private void simpleButton5_Click(object sender, EventArgs e)
        {
            try
            {
                if (txttenkh.Text == "" || txtcmnd.Text == "" || txtnn.Text == "" || txtchucvu.Text == "" || txtdiachi.Text == "")
                {
                    MessageBox.Show("Vui lòng nhập đầy đủ thông tin", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);

                }
                else if (dal.testnumber(txtcmnd.Text) == 0)
                {
                    MessageBox.Show("Số CMND chỉ được nhập số", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
                else if (dal.testcmnd(txtcmnd.Text) == 0)
                {
                    MessageBox.Show("Số CMND không hợp lệ", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
                else
                {
                    dal.SuaKH(txtmakh.Text,txttenkh.Text, txtcmnd.Text, txtnn.Text, txtchucvu.Text, txtdiachi.Text,txtemail.Text);
                    MessageBox.Show("Sửa  mã khách hàng "+txtmakh.Text+" thành công", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Asterisk);
                    Clear();
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Đã có lỗi xảy ra!");
            }
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            if (MessageBox.Show("Bạn có thật sự muốn xóa?", "Xóa Khách Hàng", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
            {
                dal.XoaKH(txtmakh.Text);
                MessageBox.Show("Xóa  mã khách hàng " + txtmakh.Text + " thành công", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Asterisk);
                Clear();
            }
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            Clear();
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            try
            {
                if (txttenkh.Text == "" && txtcmnd.Text == "" && txtnn.Text == "" && txtchucvu.Text == "" && txtdiachi.Text == "" && txtemail.Text=="")
                {
                    MessageBox.Show("Vui lòng nhập đầy đủ thông tin", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);

                }
                else if (txtcmnd.Text!="" && dal.testnumber(txtcmnd.Text) == 0)
                {
                    MessageBox.Show("Số CMND chỉ được nhập số", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }
               
                else
                {
                    var result=dal.TimKH(txttenkh.Text, txtcmnd.Text, txtnn.Text, txtchucvu.Text, txtdiachi.Text,txtemail.Text);
                    khachHangsBindingSource1.DataSource = result;
                    MessageBox.Show("Tìm kiếm khách hàng thành công", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Asterisk);
                    ClearKH();
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Đã có lỗi xảy ra!");
            }
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {
            txtmakh.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "KhachHangID").ToString();
            txttenkh.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "TenKH").ToString();
            txtcmnd.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "CMND").ToString();
            txtnn.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "NgheNghiep").ToString();
            txtchucvu.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "ChucVu").ToString();
            txtdiachi.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "DiaChi").ToString();
            txtemail.Text= gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "Email").ToString();
        }
    }
}