using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using GD_NHANVIEN.DAL;
namespace GD_NHANVIEN.GUI
{
    public partial class ThongtinKH : DevExpress.XtraEditors.XtraForm
    {
        public ThongTinHDDK f;
        public DangKySIM g;
        public HoaDonTC h;
        public ThongtinKH(ThongTinHDDK ff, DangKySIM gg, HoaDonTC hh)
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //Model.EFModel.QLCuocDTContext dbContext = new Model.EFModel.QLCuocDTContext();
            //// Call the Load method to get the data for the given DbSet from the database.
            //dbContext.KhachHangs.Load();
            //// This line of code is generated by Data Source Configuration Wizard

            var result = dal.Load();
            //khachHangsBindingSource.DataSource = result;
            if (ff == null && hh == null)
                g = gg;
            else if (gg == null && hh == null)
                f = ff;
            else if (gg == null && ff == null)
                h = hh;

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //Model.EFModel.QLCuocDTContext dbContext = new Model.EFModel.QLCuocDTContext();
            //// Call the Load method to get the data for the given DbSet from the database.
            //dbContext.KhachHangs.Load();
            //// This line of code is generated by Data Source Configuration Wizard
            //khachHangsBindingSource1.DataSource = dbContext.KhachHangs.Local.ToBindingList();
            //// This line of code is generated by Data Source Configuration Wizard
            //// Instantiate a new DBContext
            //Model.EFModel.QLCuocDTContext dbContext = new Model.EFModel.QLCuocDTContext();
            //// Call the Load method to get the data for the given DbSet from the database.
            //dbContext.KhachHangs.Load();
            //// This line of code is generated by Data Source Configuration Wizard
            //khachHangsBindingSource.DataSource = dbContext.KhachHangs.Local.ToBindingList();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //Model.EFModel.QLCuocDTContext dbContext = new Model.EFModel.QLCuocDTContext();
            //// Call the Load method to get the data for the given DbSet from the database.
            //dbContext.KhachHangs.Load();
            //// This line of code is generated by Data Source Configuration Wizard
            //khachHangsBindingSource1.DataSource = dbContext.KhachHangs.Local.ToBindingList();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            //Model.EFModel.QLCuocDTContext dbContext = new Model.EFModel.QLCuocDTContext();
            //// Call the Load method to get the data for the given DbSet from the database.
            //dbContext.KhachHangs.Load();
            // This line of code is generated by Data Source Configuration Wizard
            khachHangsBindingSource1.DataSource = result;
        }

        KhachHangDAL dal = new KhachHangDAL();
        public void Clear()
        {
            txtmakh.Clear();
            txttenkh.Clear();
            txtcmnd.Clear();
            txtchucvu.Clear();
            txtdiachi.Clear();
            txtnn.Clear();
            txtemail.Clear();
            khachHangsBindingSource1.DataSource = dal.Load();

        }
        public void ClearKH()
        {
            txtmakh.Clear();
            txttenkh.Clear();
            txtcmnd.Clear();
            txtchucvu.Clear();
            txtdiachi.Clear();
            txtnn.Clear();
            txtemail.Clear();


        }
        private void gridControl1_Click(object sender, EventArgs e)
        {
           
        }

        private void simpleButton4_Click(object sender, EventArgs e)
        {
            try
            {
                if (txttenkh.Text == "" && txtcmnd.Text == "" && txtnn.Text == "" && txtchucvu.Text == "" && txtdiachi.Text == "")
                {
                    MessageBox.Show("Vui lòng nhập đầy đủ thông tin", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);

                }
                else if (txtcmnd.Text != "" && dal.testnumber(txtcmnd.Text) == 0)
                {
                    MessageBox.Show("Số CMND chỉ được nhập số", "Lỗi", MessageBoxButtons.OK, MessageBoxIcon.Error);
                }

                else
                {
                    var result = dal.TimKH(txttenkh.Text, txtcmnd.Text, txtnn.Text, txtchucvu.Text, txtdiachi.Text,txtemail.Text);
                    khachHangsBindingSource1.DataSource = result;
                    MessageBox.Show("Tìm kiếm khách hàng thành công", "Thông báo", MessageBoxButtons.OK, MessageBoxIcon.Asterisk);
                    ClearKH();
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show("Đã có lỗi xảy ra!");
            }
        }

        private void simpleButton3_Click(object sender, EventArgs e)
        {
            Clear();
        }

        public static string MaKH;
        private void simpleButton1_Click(object sender, EventArgs e)
        {
                     
            if (txtmakh.Text == "")
            {
                MessageBox.Show("Chọn Đối tượng cần nhập");
            }
            else
            {
                if(g==null && h==null)
                {
                    f.MaKH = txtmakh.Text;
                    f.Change();
                    this.Close();
                }
                else if(f==null && h==null)
                {
                    g.MaKH = txtmakh.Text;
                    g.Change();
                    this.Close();
                }
                else if(g==null&&f==null)
                {
                    h.MaKH = txtmakh.Text;
                    h.Change1();
                    this.Close();
                }
                
            }
            
            
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void gridControl1_Click_1(object sender, EventArgs e)
        {
           
        }

        private void gridControl1_Click_2(object sender, EventArgs e)
        {
            txtmakh.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "KhachHangID").ToString();
            txttenkh.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "TenKH").ToString();
            txtcmnd.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "CMND").ToString();
            txtnn.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "NgheNghiep").ToString();
            txtchucvu.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "ChucVu").ToString();
            txtdiachi.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "DiaChi").ToString();
            txtemail.Text = gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "Email").ToString();
        }
    }
}